name: It's alive!

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust Env
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libblkid-dev libclang-dev

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - name: Build
      run: make build-debug
